morty:
  dict:
    greeting:
      - "морти"
      - "окей морти"
    action:
      - "включи"
      - "выключи"
      - "понизь яркость"
      - "повысь яркость"
      - "увеличь яркость"
      - "уменьшь яркость"
      - "скажи"
      - "подскажи"
    target:
      - "свет"
      - "лампа"
      - "лампу"
      - "кровать"
      - "зеркало"
      - "зеркале"
      - "погоду"
      - "погода"
      - "температуру"
      - "температура"
    location:
      - "кухне"
      - "спальне"
      - "зале"
      - "киеве"
      - "полтаве"