dict:
  greeting:
    - "морти"
    - "окей морти"
  action:
    включи: turn_on
    выключи: turn_off
    "понизь яркость": brighness_down
    "повысь яркость": brighness_up
    "увеличь яркость": brighness_up
    "уменьшь яркость": brighness_down
    "скажи": tell
    "подскажи": tell
  target:
    свет: lights
    лампа: lamp
    лампу: lamp
    кровать: bed
    зеркало: mirror
    зеркале: mirror
    погоду: weather
    погода: weather
    температуру: temperature
    температура: temperature
  location:
    кухне: kitchen
    спальне: bedroom
    зале: hall
    киеве: kyiv
    полтаве: poltava